In [16]:
import pandas as pd

path = "../data/parks.json"

In [17]:
df = pd.read_json(path)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      17 non-null     int64
 1   name    17 non-null     str
 2   parks   17 non-null     object
dtypes: int64(1), object(1), str(1)
memory usage: 540.0+ bytes

,id,name,parks
0,11,Cedar Fair Entertainment Company,"[{'id': 57, 'name': 'California's Great Americ..."
1,21,Chimelong Group,"[{'id': 331, 'name': 'Chimelong Birds Park', '..."
2,15,Compagnie des Alpes,"[{'id': 276, 'name': 'Bellewaerde', 'country':..."
3,17,Europa-Park,"[{'id': 51, 'name': 'Europa Park', 'country': ..."
4,10,Herschend Family Entertainment,"[{'id': 55, 'name': 'Dollywood', 'country': 'U..."

In [ ]:
df["parks"].head(1)

In [ ]:
df_normalized = df.copy()

df_normalized = df_normalized.explode('parks').reset_index(drop=True)

df_normalized = pd.json_normalize(df_normalized['parks']).add_prefix(f"parks.")


df_final = (
    df_normalized
    .drop(columns=["parks"])
    .reset_index(drop=True)
    # .join(df_exploded["parks"])
    .rename(columns={
        "id": "park_id",
        "name": "park_name",
    })
)

df_final.head()

   parks.id                        parks.name parks.parks
0        11  Cedar Fair Entertainment Company          id
1        11  Cedar Fair Entertainment Company        name
2        11  Cedar Fair Entertainment Company     country
3        11  Cedar Fair Entertainment Company   continent
4        11  Cedar Fair Entertainment Company    latitude