In [1]:
import pandas as pd

path = "../data/parks.json"

In [2]:
df = pd.read_json(path)
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      17 non-null     int64
 1   name    17 non-null     str
 2   parks   17 non-null     object
dtypes: int64(1), object(1), str(1)
memory usage: 540.0+ bytes

,id,name,parks
0,11,Cedar Fair Entertainment Company,"[{'id': 57, 'name': 'California's Great Americ..."
1,21,Chimelong Group,"[{'id': 331, 'name': 'Chimelong Birds Park', '..."
2,15,Compagnie des Alpes,"[{'id': 276, 'name': 'Bellewaerde', 'country':..."
3,17,Europa-Park,"[{'id': 51, 'name': 'Europa Park', 'country': ..."
4,10,Herschend Family Entertainment,"[{'id': 55, 'name': 'Dollywood', 'country': 'U..."

In [3]:
df["parks"].head(1)

0    [{'id': 57, 'name': 'California's Great Americ...
Name: parks, dtype: object

In [9]:
RENAME_COLUMNS_DICT = {
    "id": "group_id",
    "name": "group_name",
    "parks.id": "park_id", 
    "parks.name": "park_name",
    "parks.country": "park_country",
    "parks.continent": "park_continent",
    "parks.latitude": "park_latitude",
    "parks.longitude": "park_longitude",
    "parks.timezone": "park_timezone"
}


df_normalized = df.copy()


df_normalized = (
        df_normalized
        .pipe(lambda d: d.explode("parks").reset_index(drop=True))
        .pipe(lambda d: pd.concat([
            d.drop(columns=["parks"]),
            pd.json_normalize(d["parks"]).add_prefix("parks.")
        ], axis=1))
    )

df_normalized = df_normalized.rename(columns=RENAME_COLUMNS_DICT)

df_normalized.head()

,group_id,group_name,park_id,park_name,park_country,park_continent,park_latitude,park_longitude,park_timezone
0,11,Cedar Fair Entertainment Company,57,California's Great America,United States,North America,37.397799,-121.974717,America/Los_Angeles
1,11,Cedar Fair Entertainment Company,58,Canada's Wonderland,Canada,North America,43.843,-79.539,America/Toronto
2,11,Cedar Fair Entertainment Company,59,Carowinds,United States,North America,35.1045,-80.9394,America/New_York
3,11,Cedar Fair Entertainment Company,50,Cedar Point,United States,North America,41.4822,-82.6835,America/New_York
4,11,Cedar Fair Entertainment Company,69,Dorney Park,United States,North America,40.577942,-75.531528,America/New_York